apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: devops-test-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: devops-test-deployment
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60   # Wartezeit bevor Pods reduziert werden
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15             # Prüft alle 15 Sekunden, wie viele Pods runtergefahren werden
